### PR TITLE
closing feature #6088

### PR DESCRIPTION
**Pull request by CecileBONIN**

### CODE REVIEW

**Comment by CecileBONIN** [comment]
Please don't forget to take in account the following associated PRs :+1: 

https://github.com/Silverpeas/Silverpeas-Core/pull/588

**Comment by SilverYoCha** [comment]
As indicated for the associated PR in core, the integration can not be performed because of the failure of some unit tests. On components repository, it concerns following classes:
- AdvancedNotificationHelperTest (maillinglist)
- TestCheckNotification (maillinglist)
- TestNotificationHelper (maillinglist)
- TestMailingListComponent (maillinglist)
- TestActivitiesProcessor (maillinglist)

**Comment by CecileBONIN** [comment]
For me, all these tests are successful

**Comment by SilverYoCha** [comment]
Do you use the IDE or maven to execute the unit tests ?

**Comment by CecileBONIN** [comment]
I tried both

**Comment by SilverYoCha** [comment]
I tried again after getting the fixes of Silverpeas-Core and I still have problems. For example:
testProcessMessageSingleModerate(com.silverpeas.external.mailinglist.servlets.TestActivitiesProcessor)  Time elapsed: 0.499 sec  <<< ERROR!
java.lang.ExceptionInInitializerError: null
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1427)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1250)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:1174)
        at com.silverpeas.util.FileUtil.loadBundle(FileUtil.java:252)
        at com.stratelia.silverpeas.util.ResourceBundleWrapper.<init>(ResourceBundleWrapper.java:38)
        at com.stratelia.silverpeas.util.ResourceBundleWrapper.<init>(ResourceBundleWrapper.java:46)
        at com.stratelia.webactiv.util.ResourceLocator.getResourceBundle(ResourceLocator.java:121)
        at com.stratelia.webactiv.util.ResourceLocator.getString(ResourceLocator.java:131)
        at com.silverpeas.util.template.SilverpeasStringTemplateUtil.<clinit>(SilverpeasStringTemplateUtil.java:38)
        at com.silverpeas.util.template.SilverpeasTemplateFactory.createSilverpeasTemplateOnCore(SilverpeasTemplateFactory.java:54)
        at com.stratelia.silverpeas.notificationManager.NotificationMetaData.createTemplateMessageFooter(NotificationMetaData.java:638)
        at com.stratelia.silverpeas.notificationManager.NotificationMetaData.getTemplateMessageFooter(NotificationMetaData.java:646)
        at com.stratelia.silverpeas.notificationManager.NotificationMetaData.getContent(NotificationMetaData.java:273)
        at com.stratelia.silverpeas.notificationManager.NotificationMetaData.getContent(NotificationMetaData.java:241)
        at com.stratelia.silverpeas.notificationManager.NotificationSender.getNotificationParameters(NotificationSender.java:224)
        at com.stratelia.silverpeas.notificationManager.NotificationSender.notifyUser(NotificationSender.java:130)
        at com.stratelia.silverpeas.notificationManager.NotificationSender.notifyUser(NotificationSender.java:74)
        at com.silverpeas.mailinglist.service.notification.SimpleNotificationHelper.notifyInternals(SimpleNotificationHelper.java:132)
        at com.silverpeas.mailinglist.service.notification.SimpleNotificationHelper.notifyUsersAndModerators(SimpleNotificationHelper.java:97)
        at com.silverpeas.mailinglist.service.notification.SimpleNotificationHelper.notify(SimpleNotificationHelper.java:302)
        at com.silverpeas.external.mailinglist.servlets.MessageProcessor.moderateMessage(MessageProcessor.java:134)
        at com.silverpeas.external.mailinglist.servlets.MessageProcessor.processMessage(MessageProcessor.java:72)
        at com.silverpeas.external.mailinglist.servlets.TestActivitiesProcessor.testProcessMessageSingleModerate(TestActivitiesProcessor.java:308)

testProcessMessageModerate(com.silverpeas.external.mailinglist.servlets.TestActivitiesProcessor)  Time elapsed: 0.429 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.silverpeas.util.template.SilverpeasStringTemplateUtil
        at com.silverpeas.util.template.SilverpeasTemplateFactory.createSilverpeasTemplateOnCore(SilverpeasTemplateFactory.java:54)
        at com.stratelia.silverpeas.notificationManager.NotificationMetaData.createTemplateMessageFooter(NotificationMetaData.java:638)
        at com.stratelia.silverpeas.notificationManager.NotificationMetaData.getTemplateMessageFooter(NotificationMetaData.java:646)
        at com.stratelia.silverpeas.notificationManager.NotificationMetaData.getContent(NotificationMetaData.java:273)
        at com.stratelia.silverpeas.notificationManager.NotificationMetaData.getContent(NotificationMetaData.java:241)
        at com.stratelia.silverpeas.notificationManager.NotificationSender.getNotificationParameters(NotificationSender.java:224)
        at com.stratelia.silverpeas.notificationManager.NotificationSender.notifyUser(NotificationSender.java:130)
        at com.stratelia.silverpeas.notificationManager.NotificationSender.notifyUser(NotificationSender.java:74)
        at com.silverpeas.mailinglist.service.notification.SimpleNotificationHelper.notifyInternals(SimpleNotificationHelper.java:132)
        at com.silverpeas.mailinglist.service.notification.SimpleNotificationHelper.notifyUsersAndModerators(SimpleNotificationHelper.java:97)
        at com.silverpeas.mailinglist.service.notification.SimpleNotificationHelper.notify(SimpleNotificationHelper.java:302)
        at com.silverpeas.external.mailinglist.servlets.MessageProcessor.moderateMessage(MessageProcessor.java:134)
        at com.silverpeas.external.mailinglist.servlets.MessageProcessor.processMessage(MessageProcessor.java:72)
        at com.silverpeas.external.mailinglist.servlets.TestActivitiesProcessor.testProcessMessageModerate(TestActivitiesProcessor.java:263)

**Comment by SilverYoCha** [comment]
I fixed the problems by adding the missing bundle resource "strintemplate.properties" into test resource sources of projects that contain unit tests failures.

**Pull request merged**
